project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home #remove this to make
      - href: about.qmd
        text: Information

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



